# Generated by Django 5.1.5 on 2025-02-27 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_activity_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the destination', max_length=200)),
                ('description', models.TextField(help_text='Brief description of the destination')),
                ('location', models.CharField(help_text='Location of the destination (e.g., city, country)', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Image of the destination', null=True, upload_to='destination_images/')),
                ('best_time_to_visit', models.CharField(blank=True, help_text='Best time to visit the destination', max_length=255, null=True)),
                ('climate', models.CharField(blank=True, help_text='Climate of the destination', max_length=255, null=True)),
                ('popular_attractions', models.JSONField(blank=True, default=list, help_text="List of popular attractions (e.g., ['Pashupatinath', 'Boudhanath Stupa'])")),
                ('activities', models.ManyToManyField(blank=True, help_text='Activities available in this destination', related_name='destinations', to='travel_app.activity')),
                ('hotels', models.ManyToManyField(blank=True, help_text='Hotels available in this destination', related_name='destinations', to='travel_app.hotel')),
                ('travel_packages', models.ManyToManyField(blank=True, help_text='Travel packages available for this destination', related_name='destinations', to='travel_app.travelpackage')),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
            },
        ),
    ]
