# Generated by Django 5.1.5 on 2025-02-27 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0004_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='travel_app.activity'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='travel_app.hotel'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='travel_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='travel_app.travelpackage'),
        ),
    ]
