# Generated by Django 5.1.5 on 2025-04-09 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0006_alter_booking_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='travel_app.activity'),
        ),
        migrations.AddField(
            model_name='review',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='travel_app.hotel'),
        ),
        migrations.AlterField(
            model_name='review',
            name='travel_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='travel_app.travelpackage'),
        ),
    ]
