# Generated by Django 5.1.5 on 2025-04-11 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0007_review_activity_review_hotel_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'travel_package')},
        ),
        migrations.AddField(
            model_name='wishlist',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='travel_app.activity'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='travel_app.hotel'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='travel_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='travel_app.travelpackage'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'activity'), ('user', 'hotel'), ('user', 'travel_package')},
        ),
    ]
