# Generated by Django 5.1.5 on 2025-04-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0007_review_activity_review_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='khalti_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='khalti_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
