# Generated by Django 5.1.5 on 2025-04-12 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0008_alter_wishlist_unique_together_wishlist_activity_and_more'),
        ('travel_app', '0008_payment_khalti_status_payment_khalti_token'),
    ]

    operations = [
    ]
