# Generated by Django 5.1.5 on 2025-04-12 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0009_merge_20250412_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Wishlist', 'verbose_name_plural': 'Wishlists'},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='travel_app.activity'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='hotels',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='travel_app.hotel'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='wishlists', to='travel_app.travelpackage'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='travel_package',
        ),
    ]
